version: "3.5"
services:
  # Portainer para gerenciar os Dockerfiles
  portainer:
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    networks:
     - frontend
     - backend
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer-data:/data
    
  # microservice para controlar o BackEnd (NODEJS)
  ms-backend:
    image: 750937976472.dkr.ecr.sa-east-1.amazonaws.com/ms-backend:latest
    depends_on:
      - ms-backend
    ports:
      - "3333:3333"
    networks:
      - frontend
      - backend
    entrypoint:
      - '/usr/local/bin/docker-entrypoint.sh'

  # # microservice para controlar o FrontEnd (VUE)
  ms-frontend:
    image: 750937976472.dkr.ecr.sa-east-1.amazonaws.com/ms-frontend:latest
    depends_on:
      - ms-backend
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
  
  # microservice para fazer deploy automático para o Firebase(PQ TO COM PREGUIÇA)
   
# configuração dos networks 
networks:
  frontend:
  backend:

volumes:
  portainer-data:
