version: "3.5"
services:
  # Portainer para gerenciar os Dockerfiles
  portainer:
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    networks:
     - frontend
     - backend
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer-data:/data
    
  # microservice para controlar o Arduino
  ms-arduino:
    build: "./ms-arduino/"
    container_name: ms-arduino
    #restart: always
    privileged: true
    devices:
      - /dev:/dev
    ports:
      - ${PORT_MS_ARDUINO}
    networks:
      backend:
        ipv4_address: ${IP_MS_ARDUINO}
    entrypoint:
      - "/usr/local/bin/docker-entrypoint.sh"

  # microservice para controlar o BackEnd (NODEJS)
  ms-backend:
    build: "./ms-backend/"
    container_name: ms-backend
    restart: always
    privileged: true
    ports:
      - "3333:3333"
    networks:
      - frontend
      - backend
    entrypoint:
      - '/usr/local/bin/docker-entrypoint.sh'

  # # microservice para controlar o FrontEnd (VUE)
  ms-frontend:
    build: "./ms-frontend/"
    container_name: ms-frontend
    restart: always
    depends_on:
      - ms-backend
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
  
  # microservice para fazer deploy automático para o Firebase(PQ TO COM PREGUIÇA)
   
# configuração dos networks 
networks:
  frontend:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${SUBNET_BACKEND}

volumes:
  portainer-data:
