version: "3.5"
services:
  # Portainer para gerenciar os Dockerfiles
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    ports:
    - ${PORTAINER_PORT}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer-data:/data

  # microservice para controlar o Arduino
  ms-arduino:
    build: "./ms-arduino/"
    container_name: ms-arduino #image: hpbonfim/ardueve-microservice-arduino:latest
    privileged: true
    ports:
    - ${ARDUINO_PORT}
    devices:
    - /dev:/dev
    
  # microservice para controlar o FrontEnd (VUE)
    ms-backend:
    build: "./ms-backend/"
    container_name: ms-backend #image: hpbonfim/ardueve-microservice-backend:latest
    ports:
    - ${BACKEND_PORT}
    privileged: true

  # microservice para controlar o BackEnd (NODEJS)
    # ms-frontend:
    # build: "./ms-frontend/"
    # container_name: ms-frontend #image: hpbonfim/ardueve-microservice-frontend:latest
    # ports:
    # - ${FRONTEND_PORT}
    # privileged: true

  # microservice para controlar o Banco de Dados (MONGOOSE)
  
  # microservice para fazer deploy automático para o Firebase(PQ TO COM PREGUIÇA)

volumes:
  portainer-data: